/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alsein.crmProject.GUI;

import com.alsein.crmProject.Business.UserManager;
import com.alsein.crmProject.CrmProjectApplication;
import com.alsein.crmProject.Entities.User;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.boot.SpringApplication;

/**
 *
 * @author alims
 */
public class GuiLoginPage extends javax.swing.JFrame {
    private UserManager userManager = new UserManager(UserManager.userDal);
    static String nameOfUser = null;
    /**
     * Creates new form GuiLoginPage
     */
    public GuiLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_loginPageTitle = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        pwfield_password = new javax.swing.JPasswordField();
        txt_id = new javax.swing.JTextField();
        btn_signIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_loginPageTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_loginPageTitle.setText("JOB TRACKING APP");

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_id.setText("ID: ");

        lbl_pw.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_pw.setText("PASSWORD:");

        pwfield_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfield_passwordKeyPressed(evt);
            }
        });

        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
        });

        btn_signIn.setText("GİRİŞ");
        btn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbl_loginPageTitle)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pw)
                    .addComponent(lbl_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwfield_password)
                    .addComponent(txt_id)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_signIn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_loginPageTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pw)
                    .addComponent(pwfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_signIn)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signInActionPerformed
        checkUser();
    }//GEN-LAST:event_btn_signInActionPerformed

    private void pwfield_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfield_passwordKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            checkUser();
        }
    }//GEN-LAST:event_pwfield_passwordKeyPressed

    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            checkUser();
        }
    }//GEN-LAST:event_txt_idKeyPressed
    
    public void checkUser(){
        String pwText = new String(pwfield_password.getPassword());
        User user = userManager.get(txt_id.getText(), pwText); 
        if(user != null){
            nameOfUser = user.getNameOfUser();
            changePage(true);
        }else{
            JOptionPane.showMessageDialog(this, "Id or password is invalid. Try again.");
        }
    }
    
    private void changePage(Boolean isOkay) {
        if(isOkay){
            this.dispose();
            GuiMainPage mainPage = new GuiMainPage();
            mainPage.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SpringApplication.run(CrmProjectApplication.class, args); 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signIn;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_loginPageTitle;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JPasswordField pwfield_password;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

}
