/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alsein.crmProject.GUI;

import com.alsein.crmProject.Business.JobManager;
import com.alsein.crmProject.Business.OfferManager;
import com.alsein.crmProject.Entities.Job;
import com.alsein.crmProject.Entities.Offer;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alims
 */
public class GuiMainPage extends javax.swing.JFrame {
    private final JobManager jobManager = new JobManager(JobManager.jobDal);
    private final OfferManager offerManager = new OfferManager(OfferManager.offerDal);
    DefaultTableModel defaultTableModelActiveJobs;
    DefaultTableModel defaultTableModelDoneJobs;
    DefaultTableModel defaultTableModelActiveOffers;
    DefaultTableModel defaultTableModelDoneOffers;
    DefaultTableModel defaultTableModelAcceptOffers;
    java.util.Date date = new java.util.Date();
    String[] persons = {"person1", "person2", "person3", "person4", "person5"};
    int j = 0;
    /**
     * Creates new form GuiMainMenu
     */
    public GuiMainPage() {
        initComponents();
        writeDate();
    }

    private void writeDate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        lblCurretDate.setText(String.valueOf(dtf.format(now)));
        lblOfferCurrentDate.setText(String.valueOf(dtf.format(now)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPane = new javax.swing.JTabbedPane();
        pnlAddJob = new javax.swing.JPanel();
        lblJobCompany = new javax.swing.JLabel();
        lblJobDate = new javax.swing.JLabel();
        lblJobPerson = new javax.swing.JLabel();
        lblJobComment = new javax.swing.JLabel();
        txtJobCompany = new javax.swing.JTextField();
        cmbbxJobPerson = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaJobComment = new javax.swing.JTextArea();
        btnAddJob = new javax.swing.JButton();
        lblCurretDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActiveJobs = new javax.swing.JTable();
        btnJobDone = new javax.swing.JButton();
        btnActiveJobExpand = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDoneJobs = new javax.swing.JTable();
        btnDoneJobExpand = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblOfferCompany = new javax.swing.JLabel();
        lblOfferDate = new javax.swing.JLabel();
        lblOfferPerson = new javax.swing.JLabel();
        lblOfferComment = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaOfferComment = new javax.swing.JTextArea();
        cmbbxOfferPerson = new javax.swing.JComboBox<>();
        lblOfferCurrentDate = new javax.swing.JLabel();
        txtOfferCompany = new javax.swing.JTextField();
        btnAddOffer = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblActiveOffers = new javax.swing.JTable();
        btnOfferDone = new javax.swing.JButton();
        btnActiveOfferExpand = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDoneOffers = new javax.swing.JTable();
        btnAcceptOffers = new javax.swing.JButton();
        btnDoneOfferExpand = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblAcceptOffers = new javax.swing.JTable();
        btnAcceptOfferExpand = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 500));

        tbdPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdPaneMouseClicked(evt);
            }
        });

        lblJobCompany.setText("Firma:");

        lblJobDate.setText("Tarih:");

        lblJobPerson.setText("Yapacak Kişi:");

        lblJobComment.setText("Yapılacak İş:");

        cmbbxJobPerson.setModel(new javax.swing.DefaultComboBoxModel<>(persons));

        txtAreaJobComment.setColumns(20);
        txtAreaJobComment.setRows(5);
        jScrollPane2.setViewportView(txtAreaJobComment);

        btnAddJob.setText("EKLE");
        btnAddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddJobLayout = new javax.swing.GroupLayout(pnlAddJob);
        pnlAddJob.setLayout(pnlAddJobLayout);
        pnlAddJobLayout.setHorizontalGroup(
            pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddJobLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJobDate)
                    .addComponent(lblJobPerson)
                    .addComponent(lblJobComment))
                .addGap(18, 18, 18)
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddJobLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(pnlAddJobLayout.createSequentialGroup()
                        .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCurretDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJobCompany, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(cmbbxJobPerson, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 655, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddJobLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddJob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAddJobLayout.setVerticalGroup(
            pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddJobLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobCompany)
                    .addComponent(txtJobCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobDate)
                    .addComponent(lblCurretDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobPerson)
                    .addComponent(cmbbxJobPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobComment)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddJob)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tbdPane.addTab("İŞ EKLEME", pnlAddJob);

        tblActiveJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İŞ ID", "FİRMA ADI", "İŞ VERİLME TARİHİ", "YAPILACAK İŞ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActiveJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblActiveJobs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblActiveJobs.setShowGrid(true);
        jScrollPane1.setViewportView(tblActiveJobs);
        if (tblActiveJobs.getColumnModel().getColumnCount() > 0) {
            tblActiveJobs.getColumnModel().getColumn(0).setResizable(false);
            tblActiveJobs.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblActiveJobs.getColumnModel().getColumn(1).setResizable(false);
            tblActiveJobs.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblActiveJobs.getColumnModel().getColumn(2).setResizable(false);
            tblActiveJobs.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblActiveJobs.getColumnModel().getColumn(3).setPreferredWidth(667);
        }

        btnJobDone.setText("YAPILDI");
        btnJobDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobDoneActionPerformed(evt);
            }
        });

        btnActiveJobExpand.setText("GENİŞLET");
        btnActiveJobExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveJobExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActiveJobExpand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJobDone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJobDone)
                    .addComponent(btnActiveJobExpand))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tbdPane.addTab("AKTİF İŞLER", jPanel2);

        tblDoneJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İŞ ID", "FİRMA ADI", "İŞ VERİLME TARİHİ", "İŞ YAPILMA TARİHİ", "YAPILACAK İŞ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoneJobs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDoneJobs.setShowGrid(true);
        jScrollPane3.setViewportView(tblDoneJobs);
        if (tblDoneJobs.getColumnModel().getColumnCount() > 0) {
            tblDoneJobs.getColumnModel().getColumn(0).setResizable(false);
            tblDoneJobs.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblDoneJobs.getColumnModel().getColumn(1).setResizable(false);
            tblDoneJobs.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblDoneJobs.getColumnModel().getColumn(2).setResizable(false);
            tblDoneJobs.getColumnModel().getColumn(2).setPreferredWidth(125);
            tblDoneJobs.getColumnModel().getColumn(3).setResizable(false);
            tblDoneJobs.getColumnModel().getColumn(3).setPreferredWidth(125);
            tblDoneJobs.getColumnModel().getColumn(4).setResizable(false);
            tblDoneJobs.getColumnModel().getColumn(4).setPreferredWidth(717);
        }

        btnDoneJobExpand.setText("GENİŞLET");
        btnDoneJobExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneJobExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDoneJobExpand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoneJobExpand)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tbdPane.addTab("YAPILAN İŞLER", jPanel3);

        lblOfferCompany.setText("Firma: ");

        lblOfferDate.setText("Tarih: ");

        lblOfferPerson.setText("Yapacak Kişi:");

        lblOfferComment.setText("Yapılacak Teklif:");

        txtAreaOfferComment.setColumns(20);
        txtAreaOfferComment.setRows(5);
        jScrollPane4.setViewportView(txtAreaOfferComment);

        cmbbxOfferPerson.setModel(new javax.swing.DefaultComboBoxModel<>(persons));

        btnAddOffer.setText("EKLE");
        btnAddOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOfferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOfferComment)
                            .addComponent(lblOfferCompany)
                            .addComponent(lblOfferDate)
                            .addComponent(lblOfferPerson))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbbxOfferPerson, 0, 270, Short.MAX_VALUE)
                                    .addComponent(lblOfferCurrentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtOfferCompany))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfferCompany)
                    .addComponent(txtOfferCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfferCurrentDate)
                    .addComponent(lblOfferDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbbxOfferPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfferPerson))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfferComment)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddOffer)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tbdPane.addTab("TEKLİF EKLEME", jPanel4);

        tblActiveOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SİPARİŞ ID", "FİRMA ADI", "İŞ VERİLME TARİHİ", "YAPILACAK İŞ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActiveOffers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblActiveOffers.setShowGrid(true);
        jScrollPane5.setViewportView(tblActiveOffers);
        if (tblActiveOffers.getColumnModel().getColumnCount() > 0) {
            tblActiveOffers.getColumnModel().getColumn(0).setResizable(false);
            tblActiveOffers.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblActiveOffers.getColumnModel().getColumn(1).setResizable(false);
            tblActiveOffers.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblActiveOffers.getColumnModel().getColumn(2).setResizable(false);
            tblActiveOffers.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblActiveOffers.getColumnModel().getColumn(3).setResizable(false);
            tblActiveOffers.getColumnModel().getColumn(3).setPreferredWidth(617);
        }

        btnOfferDone.setText("YAPILDI");
        btnOfferDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfferDoneActionPerformed(evt);
            }
        });

        btnActiveOfferExpand.setText("GENİŞLET");
        btnActiveOfferExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveOfferExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActiveOfferExpand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOfferDone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOfferDone)
                    .addComponent(btnActiveOfferExpand))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tbdPane.addTab("YAPILACAK TEKLİFLER", jPanel5);

        tblDoneOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SİPARİŞ ID", "FİRMA ADI", "SİPARİŞ VERİLME TARİHİ", "SİPARİŞ YAPILMA TARİHİ", "YAPILAN TEKLİF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoneOffers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDoneOffers.setShowGrid(true);
        jScrollPane6.setViewportView(tblDoneOffers);
        if (tblDoneOffers.getColumnModel().getColumnCount() > 0) {
            tblDoneOffers.getColumnModel().getColumn(0).setResizable(false);
            tblDoneOffers.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDoneOffers.getColumnModel().getColumn(1).setResizable(false);
            tblDoneOffers.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblDoneOffers.getColumnModel().getColumn(2).setResizable(false);
            tblDoneOffers.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblDoneOffers.getColumnModel().getColumn(3).setResizable(false);
            tblDoneOffers.getColumnModel().getColumn(3).setPreferredWidth(170);
            tblDoneOffers.getColumnModel().getColumn(4).setResizable(false);
            tblDoneOffers.getColumnModel().getColumn(4).setPreferredWidth(497);
        }

        btnAcceptOffers.setText("ONAYLANDI");
        btnAcceptOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptOffersActionPerformed(evt);
            }
        });

        btnDoneOfferExpand.setText("GENİŞLET");
        btnDoneOfferExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneOfferExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDoneOfferExpand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcceptOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptOffers)
                    .addComponent(btnDoneOfferExpand))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tbdPane.addTab("YAPILAN TEKLİFLER", jPanel6);

        tblAcceptOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SİPARİŞ ID", "FİRMA ADI", "SİPARİŞ VERİLME TARİHİ", "SİPARİŞ YAPILMA TARİHİ", "SİPARİŞ ONAYLANMA TARİHİ", "YAPILAN TEKLİF", "FATURA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAcceptOffers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAcceptOffers.setShowGrid(true);
        jScrollPane7.setViewportView(tblAcceptOffers);
        if (tblAcceptOffers.getColumnModel().getColumnCount() > 0) {
            tblAcceptOffers.getColumnModel().getColumn(0).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(1).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(2).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(3).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(4).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(5).setResizable(false);
            tblAcceptOffers.getColumnModel().getColumn(6).setResizable(false);
        }

        btnAcceptOfferExpand.setText("GENİŞLET");
        btnAcceptOfferExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptOfferExpandActionPerformed(evt);
            }
        });

        btnInvoice.setText("FATURALANDIR");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInvoice)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcceptOfferExpand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptOfferExpand)
                    .addComponent(btnInvoice))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tbdPane.addTab("ONAYLANAN TEKLİFLER", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbdPane, javax.swing.GroupLayout.PREFERRED_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        String person = cmbbxJobPerson.getItemAt(cmbbxJobPerson.getSelectedIndex());
        Job job = new Job(0, txtJobCompany.getText(), getDate(), getDate(), person, txtAreaJobComment.getText(), false);
        jobManager.add(job);
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void btnJobDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobDoneActionPerformed
        int selectedRowIndex = tblActiveJobs.getSelectedRow();
        if(selectedRowIndex > -1){
            Job job = jobManager.getById((int) defaultTableModelActiveJobs.getValueAt(selectedRowIndex, 0));
            job.setEndDate(getDate());
            job.setIsDone(true);
            jobManager.update(job);
        }
        fillTheActiveJobsTable();
    }//GEN-LAST:event_btnJobDoneActionPerformed

    private void btnAddOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOfferActionPerformed
        String person = cmbbxOfferPerson.getItemAt(cmbbxOfferPerson.getSelectedIndex());
        Offer offer = new Offer(0, txtOfferCompany.getText(), getDate(), getDate(), getDate(), person, txtAreaOfferComment.getText(), false, false, false);
        offerManager.add(offer);
    }//GEN-LAST:event_btnAddOfferActionPerformed

    private void btnOfferDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfferDoneActionPerformed
        int selectedRowIndex = tblActiveOffers.getSelectedRow();
        if(selectedRowIndex > -1){
            Offer offer = offerManager.getById((int) defaultTableModelActiveOffers.getValueAt(selectedRowIndex, 0));
            offer.setEndDate(getDate());
            offer.setIsDone(true);
            offerManager.update(offer);
        }
        fillTheActiveOffersTable();
    }//GEN-LAST:event_btnOfferDoneActionPerformed

    private void btnAcceptOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptOffersActionPerformed
        int selectedRowIndex = tblDoneOffers.getSelectedRow();
        if(selectedRowIndex > -1){
            Offer offer = offerManager.getById((int) defaultTableModelDoneOffers.getValueAt(selectedRowIndex, 0));
            offer.setAcceptDate(getDate());
            offer.setIsAccept(true);
            offerManager.update(offer);
        }
        fillTheDoneOffersTable();
    }//GEN-LAST:event_btnAcceptOffersActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        int selectedRowIndex = tblAcceptOffers.getSelectedRow();
        if(selectedRowIndex > -1){
            Offer offer = offerManager.getById((int) defaultTableModelAcceptOffers.getValueAt(selectedRowIndex, 0));
            offer.setAcceptDate(getDate());
            offer.setIsInvoice(true);
            offerManager.update(offer);
        }
        fillTheAcceptOffersTable();
    }//GEN-LAST:event_btnInvoiceActionPerformed

    
    
    
    private void tbdPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdPaneMouseClicked
        int i = tbdPane.getSelectedIndex();
        
        if(i != j)
        switch (i) {
            case 1 -> fillTheActiveJobsTable();
            case 2 -> fillTheDoneJobsTable();
            case 4 -> fillTheActiveOffersTable();
            case 5 -> fillTheDoneOffersTable();
            case 6 -> fillTheAcceptOffersTable();
        }
        j=i;
    }//GEN-LAST:event_tbdPaneMouseClicked

    private void btnActiveJobExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveJobExpandActionPerformed
        runExpand();
    }//GEN-LAST:event_btnActiveJobExpandActionPerformed

    private void btnDoneJobExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneJobExpandActionPerformed
        runExpand();
    }//GEN-LAST:event_btnDoneJobExpandActionPerformed

    private void btnActiveOfferExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveOfferExpandActionPerformed
        runExpand();
    }//GEN-LAST:event_btnActiveOfferExpandActionPerformed

    private void btnDoneOfferExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneOfferExpandActionPerformed
        runExpand();
    }//GEN-LAST:event_btnDoneOfferExpandActionPerformed

    private void btnAcceptOfferExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptOfferExpandActionPerformed
        runExpand();
    }//GEN-LAST:event_btnAcceptOfferExpandActionPerformed

     private void runExpand(){
        int row = -1;
        int id = 0;
        boolean toChoose = false;
        switch (tbdPane.getSelectedIndex()) {
            case 1 -> {
                row = tblActiveJobs.getSelectedRow();
                if(row >= 0){
                id = (int) defaultTableModelActiveJobs.getValueAt(row, 0);
                toChoose = true;
                }
            }
            case 2 -> {
                row = tblDoneJobs.getSelectedRow();
                if(row >= 0){
                id = (int) defaultTableModelDoneJobs.getValueAt(row, 0);
                toChoose = true;
                }
            }
            case 4 -> {
                row = tblActiveOffers.getSelectedRow();
                if(row >= 0){
                id = (int) defaultTableModelActiveOffers.getValueAt(row, 0);
                toChoose = false;
                }
            }
            case 5 -> {
                row = tblDoneOffers.getSelectedRow();
                if(row >= 0){
                id = (int) defaultTableModelDoneOffers.getValueAt(row, 0);
                toChoose = false;
                }
            }
            case 6 -> {
                row = tblAcceptOffers.getSelectedRow();
                if(row >= 0){
                id = (int) defaultTableModelAcceptOffers.getValueAt(row, 0);
                toChoose = false;
                }
            }
        }
        if(row >= 0){
        GuiExpandPage expandPage = new GuiExpandPage(id, toChoose);
        expandPage.setVisible(true);
        }
    }
    private void fillTheActiveJobsTable() {
        defaultTableModelActiveJobs = (DefaultTableModel) tblActiveJobs.getModel();
        defaultTableModelActiveJobs.setRowCount(0);
        List<Job> jobs = jobManager.getAll();
        for(Job job: jobs){
            if(!job.getIsDone() && (GuiLoginPage.nameOfUser.equals(job.getPerson()) || GuiLoginPage.nameOfUser.equals("admin"))){
                Object[] row = {job.getId(), job.getCompanyName(), job.getDate(), job.getComment()};
                defaultTableModelActiveJobs.addRow(row);
            }
        }
    }
    
    private void fillTheDoneJobsTable() {
        defaultTableModelDoneJobs = (DefaultTableModel) tblDoneJobs.getModel();
        defaultTableModelDoneJobs.setRowCount(0);
        List<Job> jobs = jobManager.getAll();
        for(Job job: jobs){
            if(job.getIsDone() && (GuiLoginPage.nameOfUser.equals(job.getPerson()) || GuiLoginPage.nameOfUser.equals("admin"))){
                Object[] row = {job.getId(), job.getCompanyName(), job.getDate(), job.getEndDate(), job.getComment()};
                defaultTableModelDoneJobs.addRow(row);
            }
        }
    }
    
    private void fillTheActiveOffersTable() {
        defaultTableModelActiveOffers = (DefaultTableModel) tblActiveOffers.getModel();
        defaultTableModelActiveOffers.setRowCount(0);
        List<Offer> offers = offerManager.getAll();
        for(Offer offer: offers){
            if(!offer.getIsDone() && (GuiLoginPage.nameOfUser.equals(offer.getPerson()) || GuiLoginPage.nameOfUser.equals("admin"))){
                Object[] row = {offer.getId(), offer.getCompanyName(), offer.getDate(), offer.getComment()};
                defaultTableModelActiveOffers.addRow(row);
            }
        }
    }
    
    private void fillTheDoneOffersTable() {
        defaultTableModelDoneOffers = (DefaultTableModel) tblDoneOffers.getModel();
        defaultTableModelDoneOffers.setRowCount(0);
        List<Offer> offers = offerManager.getAll();
        for(Offer offer: offers){
            if(offer.getIsDone() && !offer.getIsAccept() && (GuiLoginPage.nameOfUser.equals(offer.getPerson()) || GuiLoginPage.nameOfUser.equals("admin"))){
                Object[] row = {offer.getId(), offer.getCompanyName(), offer.getDate(), offer.getEndDate(), offer.getComment()};
                defaultTableModelDoneOffers.addRow(row);
            }
        }
    }
    
    private void fillTheAcceptOffersTable() {
        defaultTableModelAcceptOffers = (DefaultTableModel) tblAcceptOffers.getModel();
        defaultTableModelAcceptOffers.setRowCount(0);
        List<Offer> offers = offerManager.getAll();
        for(Offer offer: offers){
            if(offer.getIsAccept() && (GuiLoginPage.nameOfUser.equals(offer.getPerson()) || GuiLoginPage.nameOfUser.equals("admin"))){
                Object[] row = {offer.getId(), offer.getCompanyName(), offer.getDate(), offer.getEndDate(), offer.getAcceptDate(), offer.getComment(), 
                ((offer.getIsInvoice() == true) ? "FATURALANDIRILDI" : "FATURALANDIRILMADI")};
                defaultTableModelAcceptOffers.addRow(row);
            }
        }
    }
    
    private Date getDate(){
        java.sql.Date sqlDate = new java.sql.Date(date.getTime()); 
        return sqlDate;
    } 
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GuiMainPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptOfferExpand;
    private javax.swing.JButton btnAcceptOffers;
    private javax.swing.JButton btnActiveJobExpand;
    private javax.swing.JButton btnActiveOfferExpand;
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton btnAddOffer;
    private javax.swing.JButton btnDoneJobExpand;
    private javax.swing.JButton btnDoneOfferExpand;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnJobDone;
    private javax.swing.JButton btnOfferDone;
    private javax.swing.JComboBox<String> cmbbxJobPerson;
    private javax.swing.JComboBox<String> cmbbxOfferPerson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCurretDate;
    private javax.swing.JLabel lblJobComment;
    private javax.swing.JLabel lblJobCompany;
    private javax.swing.JLabel lblJobDate;
    private javax.swing.JLabel lblJobPerson;
    private javax.swing.JLabel lblOfferComment;
    private javax.swing.JLabel lblOfferCompany;
    private javax.swing.JLabel lblOfferCurrentDate;
    private javax.swing.JLabel lblOfferDate;
    private javax.swing.JLabel lblOfferPerson;
    private javax.swing.JPanel pnlAddJob;
    private javax.swing.JTabbedPane tbdPane;
    private javax.swing.JTable tblAcceptOffers;
    private javax.swing.JTable tblActiveJobs;
    private javax.swing.JTable tblActiveOffers;
    private javax.swing.JTable tblDoneJobs;
    private javax.swing.JTable tblDoneOffers;
    private javax.swing.JTextArea txtAreaJobComment;
    private javax.swing.JTextArea txtAreaOfferComment;
    private javax.swing.JTextField txtJobCompany;
    private javax.swing.JTextField txtOfferCompany;
    // End of variables declaration//GEN-END:variables
}
